export const NICHES = [
  { id: "war", label: "⚔️ War Cipher", lang: "English", topic: "Military History" },
  { id: "science", label: "🔬 Body Horror", lang: "Telugu/English", topic: "Science Facts" },
  { id: "dopamend", label: "🧠 Dopamend", lang: "Telugu", topic: "Science Curiosity" },
  { id: "polemod", label: "🤖 Polemod", lang: "English", topic: "AI Debate" },
  { id: "devops", label: "💻 DevOps/Tech", lang: "English", topic: "Tech Career" },
];

export const FRAMEWORK = [
  { key: "tam", step: "01", label: "High TAM Idea", desc: "Topic interesting to MANY, not few" },
  { key: "hook1", step: "02", label: "Curiosity in 3s", desc: "Most think X — BUT actually Y" },
  { key: "hook2", step: "03", label: "Super Hook", desc: "Line 2: Why should I listen to you?" },
  { key: "line3", step: "04", label: "Speed 2 Value", desc: "Line 3: Dive into value immediately" },
  { key: "body", step: "05", label: "Create Tension", desc: "Use BUT and SO — not 'and then'" },
];

export const SCRIPTS = {
  war: [
    {
      title: "The Weapon That Nearly Won WW2",
      tam: "WW2 secret weapons most people never heard of",
      hook1: "Most people think Hitler lost WW2 because of bad strategy — BUT he actually came THIS close to winning with one weapon.",
      hook2: "I've spent 200+ hours analyzing declassified military archives.",
      line3: "Here's the weapon that nearly changed history forever:",
      body: [
        "The V-2 rocket program killed more slave laborers building it than Allied soldiers it destroyed.",
        "BUT it scared the world into the Space Race.",
        "SO the Nazis accidentally launched human civilization into orbit.",
        "Every rocket that ever flew? Traces back to this single weapon.",
      ],
      cta: "Drop a 🚀 if you never knew this.",
    },
    {
      title: "The Real Reason Japan Surrendered",
      tam: "The real reason Japan surrendered in WW2",
      hook1: "Most historians say Japan surrendered because of the atomic bombs — BUT the real reason was kept secret for 50 years.",
      hook2: "I studied 3 declassified NSA documents that prove this.",
      line3: "Here's what actually ended the Pacific War:",
      body: [
        "Soviet Russia declared war on Japan on August 8th — the same week as Hiroshima.",
        "BUT no one talks about this.",
        "SO Japan didn't fear America destroying cities. They feared Soviet occupation.",
        "Two bombs didn't end the war. One declaration did.",
      ],
      cta: "Share this if your history teacher lied to you.",
    },
    {
      title: "The Nazi Wonder Weapons Program",
      tam: "Hitler's secret wonder weapons almost won WW2",
      hook1: "Most people think WW2 was won by better tactics — BUT Germany had weapons in 1945 that were 20 years ahead of their time.",
      hook2: "I cross-referenced 5 military engineering archives to find these.",
      line3: "Here are the 3 weapons that almost rewrote history:",
      body: [
        "The Horten Ho 229 was a stealth jet bomber invisible to radar — BUT it was completed only 3 months before Germany surrendered.",
        "SO the Allies never faced it in combat.",
        "Had it launched 6 months earlier, the war map looks entirely different.",
      ],
      cta: "Follow for more classified military history 🎖️",
    },
  ],
  science: [
    {
      title: "What Happens When You Hold Your Breath",
      tam: "What happens inside your body when you hold your breath",
      hook1: "Most people think holding your breath is harmless — BUT after 60 seconds your blood does something terrifying.",
      hook2: "I read 12 medical studies so you don't have to.",
      line3: "Here's the body horror nobody warns you about:",
      body: [
        "Your brain starts killing neurons after 4 minutes of no oxygen.",
        "BUT the first thing to shut down is your sense of danger.",
        "SO you feel calm right before brain damage begins.",
        "Nature made dying feel peaceful. That's the real curse.",
      ],
      cta: "Follow if this disturbed you 🧠",
    },
    {
      title: "The Parasite That Controls Your Mind",
      tam: "The parasite that controls human behavior",
      hook1: "Most people think they control their own thoughts — BUT 40% of humans carry a parasite that rewires their brain.",
      hook2: "Neuroscience papers confirmed this in 2019.",
      line3: "Here's what Toxoplasma gondii actually does to you:",
      body: [
        "It makes infected men more risk-taking and infected women more social.",
        "BUT scientists can't remove it once it's inside.",
        "SO if you've ever owned a cat, there's a real chance something else is influencing your decisions.",
        "Free will might be a parasite's marketing strategy.",
      ],
      cta: "Tag someone who owns a cat 🐱",
    },
    {
      title: "Your Skin Is Eating You Alive",
      tam: "The microscopic horror living on your face right now",
      hook1: "Most people think their skin is clean — BUT right now, thousands of creatures are feeding on your face.",
      hook2: "Dermatology research confirmed this is literally happening to you.",
      line3: "Here's the body horror you can't unsee:",
      body: [
        "Demodex mites live inside your hair follicles and eat your skin oil — no eyes, no anus, they just eat and die inside your pores.",
        "BUT removing them would actually make things worse.",
        "SO your face is their home and you have no say in the matter.",
        "You're not a person. You're a habitat.",
      ],
      cta: "Share if you're now deeply uncomfortable 😳",
    },
  ],
  dopamend: [
    {
      title: "మెదడు నిద్రని ఎందుకు resist చేస్తుంది",
      tam: "మన మెదడు ఎందుకు నిద్రపోవడానికి ఇష్టపడదు",
      hook1: "చాలామంది అనుకుంటారు నిద్ర రాకపోవడం stress వల్ల — BUT actually మీ brain మిమ్మల్ని చంపాలని చూస్తుంది.",
      hook2: "నేను 50+ neuroscience papers చదివాను — ఇది నిజంగా scary.",
      line3: "ఇక్కడ ఉంది brain చేసే అసలు పని రాత్రిపూట:",
      body: [
        "మీరు నిద్రపోయినప్పుడు brain మీ toxic waste flush చేస్తుంది.",
        "BUT మీరు నిద్ర avoid చేస్తే ఆ poison మీ neurons లో build up అవుతుంది.",
        "SO ప్రతి late night scroll మీ brain ని literally poison చేస్తుంది.",
        "Phone వదల్లేకపోవడం మీ weakness కాదు — అది brain chemistry.",
      ],
      cta: "Follow చేయండి, రోజూ ఇలాంటి facts చెప్తాను 🧠",
    },
    {
      title: "Dopamine Trap అంటే ఏమిటి",
      tam: "Social media మనల్ని ఎందుకు addicted చేస్తుంది",
      hook1: "చాలామంది అనుకుంటారు willpower లేక phone వదలలేమని — BUT actually మీ brain ని deliberately hijack చేశారు.",
      hook2: "Silicon Valley engineers ఇదే design చేశారు — నాకు తెలుసు ఎందుకంటే నేను papers చదివాను.",
      line3: "ఇక్కడ ఉంది అసలు science:",
      body: [
        "Likes, comments — ఇవి random గా వస్తాయి, predictable గా కాదు.",
        "BUT random rewards మన brain లో slot machine effect create చేస్తాయి.",
        "SO మీరు scroll చేస్తూ ఉంటారు — ఎప్పుడు reward వస్తుందో తెలియదు కాబట్టి.",
        "మీకు addiction లేదు — మీకు engineered trap ఉంది.",
      ],
      cta: "Save చేయండి — మీ friends కి show చేయండి 📲",
    },
  ],
  polemod: [
    {
      title: "Should AI Replace Human Doctors?",
      tam: "Should AI replace human doctors?",
      hook1: "Most people think AI replacing doctors is years away — BUT it already made a diagnosis human doctors missed for 3 years.",
      hook2: "4 AI minds just argued about this. The answer will surprise you.",
      line3: "Here's what ChatGPT, Gemini, Claude, and Grok each said:",
      body: [
        "ChatGPT said: efficiency over emotion — doctors are bottlenecks.",
        "BUT Claude disagreed: trust cannot be programmed, only earned.",
        "SO Gemini tried to split the difference — and Grok called both of them cowards.",
        "The real answer isn't what any of them said.",
      ],
      cta: "Which AI do you agree with? Comment below 👇",
    },
    {
      title: "Is Lying Ever Morally Justified?",
      tam: "Is lying ever morally justified?",
      hook1: "Most people say lying is always wrong — BUT every single one of them has lied to protect someone they love.",
      hook2: "4 AIs with 4 completely different moral frameworks just debated this.",
      line3: "Here's where each one landed:",
      body: [
        "ChatGPT said: context determines morality — lying to save a life is justified.",
        "BUT Grok said: the moment you justify one lie, all lies become negotiable.",
        "SO Claude argued: it's not about the lie — it's about what you're protecting.",
        "Gemini said they were all missing the point entirely.",
      ],
      cta: "Who do you agree with? Drop your AI below 🤖",
    },
  ],
  devops: [
    {
      title: "How to Get Hired as Senior DevOps at MNC",
      tam: "How to get hired as a Senior DevOps Engineer at an MNC",
      hook1: "Most DevOps engineers apply to 100 jobs and hear nothing — BUT the ones getting hired at MNCs all do one counterintuitive thing.",
      hook2: "I've cracked 3 MNC interviews after 5 years in CI/CD, GCP, and GKE.",
      line3: "Here's the single thing that changed everything for me:",
      body: [
        "Companies don't hire skills — they hire proof of impact.",
        "BUT anyone can say 'I know Kubernetes' on a resume.",
        "SO saying 'I reduced deployment failures by 40% using Harness rollback policies' gets you shortlisted.",
        "Stop listing tools. Start listing outcomes.",
      ],
      cta: "Save this if you're job hunting in DevOps 💾",
    },
    {
      title: "The GCP Skill That Gets You Hired",
      tam: "The one GCP skill senior engineers always ask about",
      hook1: "Most DevOps engineers study GCP certifications to get hired — BUT the one skill interviewers actually test is something certifications never teach.",
      hook2: "I've interviewed at 4 MNCs and this came up every single time.",
      line3: "Here's what they actually want to see:",
      body: [
        "They want you to debug a failing GKE pod live — not explain what a pod is.",
        "BUT most candidates memorize theory and freeze on real scenarios.",
        "SO practice: kubectl logs, kubectl describe, and reading Stackdriver traces until it's muscle memory.",
        "Certifications get you the call. War stories get you the offer.",
      ],
      cta: "Follow for more MNC interview secrets 🎯",
    },
  ],
};
